### ISSUE TITLE
XAML Preview not working

### ISSUE THREAD

**Issue by slydlake** [koechlm/VDS-Sample-Configuration-2022#8]
Hey Markus,

wanted to preview the XAML files in Visual Studio 2022. I fixed the reference links. But I always get an error, that assemblies are missing. Can you see what is missing
![XAML Error](https://user-images.githubusercontent.com/8127898/169009794-7f17765e-08a4-4e43-aa00-6829ba928b9e.png)
?

**Comment by koechlm** [comment]
Hi Timon, you need to use Visual Studio 2019.
